### ISSUE TITLE
Doesn't work on M1 mac

### ISSUE THREAD

**Issue by Snitzle** [rl404/akatsuki#131]
When trying to run through the instructions on docker I get this message when trying to pull:

```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

And this error when trying to build it:

```
make: go: No such file or directory
make: *** [clean] Error 1
```

Edit: This can be resolved for the build error by removing below from the docker file 

```
GOARCH=amd64
```

It would be worth stating in the docs that you need to create a MAL account and set up and API app, which I discovered through looking through the env.

I also encountered this error: 

```
akatsuki-migrate  | Error: dial tcp [::1]:3306: connect: connection refused
```

which can be resolved by changing the address to this, although this appears to be a general docker error: 

```
AKATSUKI_DB_ADDRESS=docker.for.mac.localhost:3306
```

**Comment by rl404** [comment]
Ah yes the common problem for M1 mac. And it's kinda my fault too since I'm always using linux (ubuntu) when developing. Sure, I will try to fix the docker file as you suggested.

About the MAL account and API key, I seem to forget the put it in the requirement section. Thanks for the reminder.
